workflows:
  ios-simulator:
    name: iOS Simulator Build for Testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter clean & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      - name: Build for iOS Simulator
        script: |
          # Build specifically for simulator (no code signing needed)
          flutter build ios --simulator --debug --verbose
          
          # Verify the .app was created
          ls -la build/ios/iphonesimulator/
          
          # Create zip for easier upload
          cd build/ios/iphonesimulator/
          zip -r Runner-simulator.zip Runner.app/
          
          # Also create IPA-like structure that some platforms expect
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Runner-simulator.ipa Payload/

    artifacts:
      - build/ios/iphonesimulator/Runner.app/**/*
      - build/ios/iphonesimulator/Runner-simulator.zip
      - build/ios/iphonesimulator/Runner-simulator.ipa