workflows:
  ios-app:
    name: iOS App
    environment:
      xcode: latest
    scripts:
      - name: Build ipa
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR
