workflows:
  ios-browserstack:
    name: iOS build for BrowserStack
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # Step 1: Prepare Flutter
      - name: Flutter clean & get deps
        script: |
          flutter clean
          flutter pub get

      # Step 2: Build iOS app (no signing, for real devices)
      - name: Build iOS release (no signing)
        script: |
          flutter build ios --release --no-codesign

      # Step 3: Archive and export IPA
      - name: Create IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

          # Use exportOptions.plist in ios/
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
