workflows:
  ios-simulator:
    name: iOS Simulator Build for Testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build for iOS Simulator
        script: |
          # Build specifically for simulator (no code signing needed)
          flutter build ios --simulator --debug --verbose
          
          # Verify the .app was created and check its contents
          ls -la build/ios/iphonesimulator/
          ls -la build/ios/iphonesimulator/Runner.app/
          
          # Check if Flutter framework is embedded
          ls -la build/ios/iphonesimulator/Runner.app/Frameworks/
          
          # Create zip for easier upload
          cd build/ios/iphonesimulator/
          zip -r Runner-simulator.zip Runner.app/

    artifacts:
      - build/ios/iphonesimulator/Runner.app/**/*
      - build/ios/iphonesimulator/Runner-simulator.zip

  ios-device:
    name: iOS Device Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean & get dependencies
        script: |
          flutter clean
          flutter pub get
          flutter pub deps

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      - name: Build for iOS Device
        script: |
          # Build for device
          flutter build ios --release --verbose
          
          # Verify the .app was created
          ls -la build/ios/iphoneos/
          ls -la build/ios/iphoneos/Runner.app/
          
          # Check if Flutter framework is embedded
          ls -la build/ios/iphoneos/Runner.app/Frameworks/

    artifacts:
      - build/ios/iphoneos/Runner.app/**/*