name: medical_transcription
description: Medical transcription app with real-time audio streaming
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  provider: ^6.1.0
  permission_handler: ^11.0.1
  path: ^1.8.3
  uuid: ^4.1.0
  dynamic_color: ^1.6.8
  material_color_utilities: ^0.11.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true