# Use Node.js 18 LTS
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Create uploads directory
RUN mkdir -p uploads public

# Create simple index.html if it doesn't exist
RUN echo '<!DOCTYPE html><html><head><title>Medical Scribe API</title></head><body><h1>Medical Scribe API Server</h1><p>Server is running on port 3000</p><ul><li>POST /upload-session</li><li>POST /get-presigned-url</li><li>POST /upload-chunk/:sessionId/:chunkNumber</li><li>POST /notify-chunk-uploaded</li><li>GET /all-session</li><li>GET /health</li></ul></body></html>' > public/index.html

# Expose port
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]